# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/SH/Desktop/Tetris/Tetris.runs/synth_1/Main.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a12ticsg325-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/SH/Desktop/Tetris/Tetris.cache/wt [current_project]
set_property parent.project_path C:/Users/SH/Desktop/Tetris/Tetris.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/SH/Desktop/Tetris/Tetris.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/grid_I.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/grid_S.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_9.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/grid_J.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/arror_left.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/T.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_7.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/grid_T.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_0.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/pause.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/hold.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/L.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_8.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_6.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/grid_Z.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/arror_right.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/S.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/game_over.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/t_spin.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/I.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_5.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/pick_map.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/next.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/images.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/J.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/1215.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/Z.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/illustration.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_3.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/grid_O.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/triple.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/board.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_4.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/background.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_1.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/start.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/grid_L.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/double.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/score_picture.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/O.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/number_2.mem
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/mem_file/shadow.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/imports/LCD_module.v
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/imports/clk_divider.v
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/imports/debounce.v
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/imports/sram.v
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/imports/sram_buf.v
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/imports/sram_number.v
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/imports/vga_sync.v
  C:/Users/SH/Desktop/Tetris/Tetris.srcs/Main.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/SH/Desktop/Tetris/Tetris.srcs/constrs_1/new/tetris.xdc
set_property used_in_implementation false [get_files C:/Users/SH/Desktop/Tetris/Tetris.srcs/constrs_1/new/tetris.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Main -part xc7a12ticsg325-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
